import Head from "next/head";
import Link from "next/link";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import i18nextconfig from "../../next-i18next.config.mjs";
import { api } from "~/utils/api";
import LanguageSelector from "~/components/languageSelector";
import NavBar from "~/components/navbar";
import { Button } from "~/components/ui/button";
import Marquee from "~/components/layout/marquee";

export const getStaticProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"], i18nextconfig, [
      "fr",
      "es",
      "en",
    ])),
  },
});

function Test(props: { element?: { label: string } }) {
  return <a className="text-red-500">{props.element.label}</a>;
}

export default function Home() {
  const { t } = useTranslation();
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <NavBar
            links={[
              { label: "Test", link: "/" },
              { label: "Language", component: <LanguageSelector minimize /> },
              { label: "Button", component: <Button>Lool</Button> },
            ]}
            logo="/assets/logo/logo.svg"
          />
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <LanguageSelector />
          <p className="text-xl text-white">{t("language.name")}</p>
          <Marquee
            repeat={12}
            elements={[{ label: "test1" }]}
            time="12s"
            component={<Test />}
          />
        </div>
      </main>
    </>
  );
}
